version: '3.8'

services:
  db:
    image: docker.io/library/postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: monitor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: docker.io/dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: juliopvalim@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:

